name: pjt_ditto_front
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ^3.6.0

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    firebase_core: ^3.10.1
    intl: ^0.19.0

    cupertino_icons: ^1.0.8
    flutter_dotenv: ^5.2.1
    animated_text_kit: ^4.2.2
    firebase_auth: ^5.3.4

    http: ^0.13.4

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    assets:
        - .env

    # To add assets to your application, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg

    fonts:
        - family: NotoSansJPExtraBold
          fonts:
              - asset: fonts/NotoSansJP/NotoSansJP-ExtraBold.ttf
        - family: NotoSansJPRegular
          fonts:
              - asset: fonts/NotoSansJP/NotoSansJP-Regular.ttf
        - family: NotoSerifJPBold
          fonts:
              - asset: fonts/NotoSerifJP/NotoSerifJP-Bold.ttf
