// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEqki9lXQc3TMRMkhJfrrusdB_7dYWVXQ',
    appId: '1:359175484022:web:cdd88e6713a7342af1e557',
    messagingSenderId: '359175484022',
    projectId: 'show-your-ai',
    authDomain: 'show-your-ai.firebaseapp.com',
    storageBucket: 'show-your-ai.firebasestorage.app',
    measurementId: 'G-HRD2TSG0KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2CdLzo7zeDZQHaQrrYR5Mv0PrhFrYF6s',
    appId: '1:359175484022:android:287807bb4b1ea2c3f1e557',
    messagingSenderId: '359175484022',
    projectId: 'show-your-ai',
    storageBucket: 'show-your-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0SuXJpvKFRFIj-ci9La5cJr36qJZFxdM',
    appId: '1:359175484022:ios:50c903de010e9fb7f1e557',
    messagingSenderId: '359175484022',
    projectId: 'show-your-ai',
    storageBucket: 'show-your-ai.firebasestorage.app',
    iosClientId: '359175484022-mpmearejme6b8shj7ikc2aspgl0uo866.apps.googleusercontent.com',
    iosBundleId: 'com.example.pjtDittoFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0SuXJpvKFRFIj-ci9La5cJr36qJZFxdM',
    appId: '1:359175484022:ios:50c903de010e9fb7f1e557',
    messagingSenderId: '359175484022',
    projectId: 'show-your-ai',
    storageBucket: 'show-your-ai.firebasestorage.app',
    iosClientId: '359175484022-mpmearejme6b8shj7ikc2aspgl0uo866.apps.googleusercontent.com',
    iosBundleId: 'com.example.pjtDittoFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEqki9lXQc3TMRMkhJfrrusdB_7dYWVXQ',
    appId: '1:359175484022:web:fb5c967966e3bd19f1e557',
    messagingSenderId: '359175484022',
    projectId: 'show-your-ai',
    authDomain: 'show-your-ai.firebaseapp.com',
    storageBucket: 'show-your-ai.firebasestorage.app',
    measurementId: 'G-1K26Z13Y8P',
  );

}