name: flutter_ci

on:
    push:

jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Create flutter environment
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.27.1"
                  channel: "stable"
                  cache: true
            - name: Install packages
              run: flutter pub get
            - name: Check format
              run: dart format lib --set-exit-if-changed -o none
            - name: Analyze
              run: flutter analyze
            - name: Test
              run: flutter test
